### ISSUE TITLE
Diagnostic plot and should_I_decorr not working in version 0.8.1

### ISSUE THREAD

**Issue by gbruno88** [pmaxted/pycheops#128]
Here are the logs. 

Thank you, 
Giovanni

=================================================================

dataset.should_I_decorr()
Traceback (most recent call last):

 File "<ipython-input-9-dc857b2a374a>", line 1, in <module>
 dataset.should_I_decorr()

 File "/dati/software/anaconda3/envs/cheops/lib/python3.7/site-packages/pycheops/dataset.py", line 2791, in should_I_decorr
 min_BIC = copy.copy(result.bic)

 AttributeError: 'function' object has no attribute 'copy'

====================================================================

 dataset.diagnostic_plot()
Traceback (most recent call last):

  File "<ipython-input-10-83d79f59abd5>", line 1, in <module>
    dataset.diagnostic_plot()

  File "/dati/software/anaconda3/envs/cheops/lib/python3.7/site-packages/pycheops/dataset.py", line 2561, in diagnostic_plot
    flux_measure = copy.copy(flux)

AttributeError: 'function' object has no attribute 'copy'

**Comment by ThomasGWilson** [comment]
Hi Giovanni,

Thanks for the report. Dataset.py has been patched and this should be fixed in 0.8.2.

Thanks,

Tom

**Comment by delinea** [comment]
Hi Tom,
As `dataset.should_I_decorr()` is being patched, there are some empty `print()` in version 0.8.1 that have likely been forgotten there (lines 2807 and 2815 in dataset.py)
Thanks

**Comment by ThomasGWilson** [comment]
Thanks, these have been removed in the next patch.
